### ISSUE TITLE
Timer Task Prioritization Causing Queue to Overflow

### ISSUE THREAD

**Issue by wavious-jbasista** [waviousllc/wav-lpddr-sw#56]
When doing multiple frequency switches during training, it was seen that the timer task would get starved due to prioritization levels which would cause timer events to fail when trying to add to the queue.  Increasing the timer task priority to max fixes this and allows the queue to not overflow, but can cause additional timing delays when considering context switching.  Need to investigate if there is a priority value which can be applied to the timer task allowing for queue to empty when lowering priority of main task but not touching priority of other tasks in the system.

**Comment by wavious-wpatty** [comment]
No longer applicable. Firmware redesign removed this issue.

**Comment by wavious-wpatty** [comment]
No longer applicable. Firmware redesign removed this issue.
